version: '2'

services:
  app:
    build: ./app
    image: titanjer/docker-flask-app

  nginx:
    build: ./nginx
    image: titanjer/docker-flask-nginx
    ports:
      - "80:80"
    volumes_from:
      - app:rw
